' Gambas module file

Private hlb As Label
Private hpb As ProgressBar

Public Sub Verif_Version()
  
  If Settings["/dbase/Version"] = "LXpos V1.0" Or If Settings["/dbase/Version"] = "LXpos V1.2" Then 
    Maj()
    Maj12()
    Settings["/dbase/Version"] = "LXpos V1.3"
    Settings.save
    Try Kill User.home & "/Caisse.lock"
  Else
    Message.Info("Aucune mise à jour n'est a faire !")
    Maj12()
  Endif
  
  If Settings["/dbase/Version"] = "LXpos V1.3" Then 
    Maj()
    Maj13()
    Settings["/dbase/Version"] = "LXpos V1.4"
    Settings.save
    Try Kill User.home & "/Caisse.lock"
  Else
    Message.Info("Aucune mise à jour n'est a faire !")
    Maj13()
  Endif
  
  Settings.Save
  Settings.Reload
  
End

Public Sub Maj()
  
  Dim $hform As Form
  Dim hLabel As Label
  
  $hForm = New Form As "Form"
  $hform.Width = 600
  $hform.Height = 400
  $hForm.Border = Border.Etched
  $hform.Title = "Mise à jour de LX.pos"
  hLabel = New Label($hForm)
  hLabel.Text = "La mise à jour prend un peu de temps.\n Veuillez patienter SVP."
  hLabel.Width = 600
  hLabel.Alignment = Align.center
  hLabel.Height = 40
  hLabel.Y = 12
  'hLabel.Border = Border.Plain
  hlb = New Label($hForm)
  hlb.Width = 600
  hlb.Height = 20
  hlb.Y = 70
  hlb.Alignment = Align.center
  hpb = New ProgressBar($hForm)
  hpb.Width = 400
  hpb.Height = 20
  hpb.X = 100
  hpb.Y = 100
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 600, 200)
  $hform.Center
  If Exist(User.Home & "/LXpos.tar.gz") Then Kill User.Home & "/LXpos.tar.gz"
  Shell "wget -q" & " " & "http://www.laurux.fr/file/version.txt" & " -P " & User.Home Wait
  If Exist(User.Home & "/version.txt") Then
    If Message.Question("Attention ! Vous allez mettre à jour votre logiciel Caisse LX-Pos\n Vous devez être connecté au réseau internet. \n Etes-vous d'accord ?", "Oui", "Non") = "1" Then
      Try Move Application.Path & "/LX-Pos.gambas" To Application.Path & "/LX-Pos.old.gambas"
      Shell "cd " & User.Home
      $hForm.Show
      Wait 1
      $hform.Mouse = Mouse.Wait
      Shell "wget http://www.laurux.fr/file/LX-Pos.tar.gz -P " & User.Home & " -o ~/tmp/pb1.txt"
      Avancement()
      Shell "cd " & User.Home & " " & "; tar xvfz " & User.Home & "/LXpos.tar.gz" Wait
      Wait 2
      Kill User.Home & "/LXpos.tar.gz"
      Kill User.Home & "/version.txt"
      $hform.Mouse = Mouse.Default
      $hform.Close
      Message.Warning("Mise à jour terminée ! Veuillez relancer LX-Pos SVP !")
    Endif
  Else
    $hform.Mouse = Mouse.Default
    Message.Warning("Problème de mise à jour! Veuillez vérifier votre connexion SVP.")
  Endif
Catch
  Music.Load(Start.Musique)
  Music.Play
  message.Error(Error.Text & " " & Error.where)
  
End

Public Sub Avancement()
  
  Dim hFile As File
  Dim chaine As String
  Dim v As Integer
  Dim numligne As Integer
  Dim L3 As String = "0"
  
  numligne = 0
  v = 0
  Do While Not Exist(User.home & "/tmp/pb1.txt")  'On test l'existence du fichier temporaire
  Loop
  Wait 0.1
  Do While L3 <> "100"      'On test la fin du téléchargement
    hFile = Open User.home & "/tmp/pb1.txt" For Input
    numligne = 0
    While Not Eof(hFile)
      Line Input #hFile, chaine
      If v = 100 Then L3 = "100"
      If Mid(chaine, 7, 2) = "K " And Len(chaine) <= 78 And Len(chaine) >= 75 Then
        L3 = Mid(chaine, 63, 3)
        If CInt(L3) > v Then  'On incrémente la barre de progression
          v = CInt(L3)
          Hpb.Value = CInt(L3) / 100
          hlb.Text = Chaine
        Endif
      Else
        Wait
      Endif
    Wend
    Close #hFile
  Loop
  'CLOSE #hFile
  Try Kill User.Home & "/tmp/pb1.txt"  '--- Suppression du fichier temporaire ---
  
End

Public Sub Maj12()
  
  Dim Tab As String
  
  Tab = "Fiches_Touches" 
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (coul INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fond varchar(100))")
  
End

Public Sub Maj13()
  
  Dim Tab As String
  
  Tab = "Fiches_Touches" 
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (touche_s tinyint(1))")
  Utils.db.Exec("ALTER TABLE " & Tab & " change touche touche Char(6)")
  
End
